"""Initial revision

Revision ID: 560e14c22eda
Revises: 9d59444a9abe
Create Date: 2024-05-21 10:45:02.249090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560e14c22eda'
down_revision: Union[str, None] = '9d59444a9abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('authors', 'last_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('post_tags_tag_id_fkey', 'post_tags', type_='foreignkey')
    op.drop_constraint('post_tags_post_id_fkey', 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_category_id_fkey', 'posts', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'authors', ['author_id'], ['id'])
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key('post_tags_post_id_fkey', 'post_tags', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('post_tags_tag_id_fkey', 'post_tags', 'tags', ['tag_id'], ['id'])
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('authors', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('authors', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
