"""4

Revision ID: 80acc2765640
Revises: 59f2e5221a6c
Create Date: 2024-05-21 15:41:19.524207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80acc2765640'
down_revision: Union[str, None] = '59f2e5221a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.drop_column('authors', 'last_name')
    op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_tags_name', table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.drop_column('posts', 'updated_at')
    op.drop_column('categories', 'description')
    op.add_column('authors', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_column('authors', 'email')
    # ### end Alembic commands ###
